//
//  QuotesData.swift
//  FamousQuoteGeneratorForJojoApp
//
//  Created by にしいけんすけ on 2024/05/26.
//

import Foundation

struct Quote {
    let quote: String
    let characterName: String
}

struct QuotesData {
    // 1部
    static let quote1 = [
        Quote(quote: "ふるえるぞハート!\n燃えつきるほどヒート!!\nおおおおおっ\n刻むぞ血液のビート!",
              characterName: "ジョナサン・ジョースター"),
        Quote(quote: "なっ!\n何をするんだァーーーーーーッ\nゆるさんッ!",
              characterName: "ジョナサン・ジョースター"),
        Quote(quote: "歴史の\n闇に\n永遠に\n沈め!",
              characterName: "ジョナサン・ジョースター"),
        Quote(quote: "ぼくは\n本当の紳士を\nめざしているからだ!",
              characterName: "ジョナサン・ジョースター"),
        Quote(quote: "「策」ではないッ!\n「勇気」だッ!!",
              characterName: "ジョナサン・ジョースター"),
        Quote(quote: "ぼくの青春は\nディオとの青春!\nこれからその青春に\n決着をつけてやるッ!",
              characterName: "ジョナサン・ジョースター"),
        Quote(quote: "ぼくには指4本など\n失ってもいい理由がある!\nそれは父を守るため!\nジョースター家を守るため!\n君らとは戦う動機の\n「格」が違うんだ!",
              characterName: "ジョナサン・ジョースター"),
        Quote(quote: "ぼくは……\n父のためにここに来た……\nだから蹴る瞬間!\n君にも父や母や兄弟が\nいるはずだと思った……\n君の父親が悲しむことは\nしたくないッ!",
              characterName: "ジョナサン・ジョースター"),
        Quote(quote: "あんな\nクズに\n名誉など\nあるものかァーーーッ!!",
              characterName: "ジョナサン・ジョースター"),
        Quote(quote: "さびしいよ\n…………ああ\nぼくは　こうして\n悲しみのまま\n涙でずぶぬれになって\n死んでいくんだ",
              characterName: "ジョナサン・ジョースター"),
        Quote(quote: "君がッ\n泣くまで\n殴るのをやめないッ!",
              characterName: "ジョナサン・ジョースター"),
        Quote(quote: "信念さえあれば\n人間に不可能はない!\n人間は成長するのだ!",
              characterName: "ジョナサン・ジョースター"),
        Quote(quote: "貧弱!\n貧弱ゥ!",
              characterName: "ディオ・ブランドー"),
        Quote(quote: "おまえは今まで\n食ったパンの枚数を\nおぼえているのか？",
              characterName: "ディオ・ブランドー"),
        Quote(quote: "UREEYYY!!",
              characterName: "ディオ・ブランドー"),
        Quote(quote: "孤独は\n人間をカラッポにするからな!\nヤツを無気力な\nフヌケにしてやる!",
              characterName: "ディオ・ブランドー"),
        Quote(quote: "ジョジョ!\nその薬を調べるという事は\n我われの友情を疑う事!\n友情を失うぞッ!",
              characterName: "ディオ・ブランドー"),
        Quote(quote: "モンキーが人間に\n追いつけるかーッ\nおまえは\nこのディオにとっての\nモンキーなんだよ\nジョジョォォォォ\nーーーーーッ!!",
              characterName: "ディオ・ブランドー"),
        Quote(quote: "ファンファーレ\nでも吹いているのが\n似あっているぞッ!",
              characterName: "ディオ・ブランドー"),
        Quote(quote: "おれは人間をやめるぞ!\nジョジョーーーッ!!\nおれは\n人間を\n超越するッ!",
              characterName: "ディオ・ブランドー"),
        Quote(quote: "酒!\n飲まずには\nいられないッ!",
              characterName: "ディオ・ブランドー"),
        Quote(quote: "あの父親の精神は…………………\n息子のジョナサン・ジョースターが\n立派に受け継いでいる!\nそれは彼の強い意志となり\n誇りとなり\n未来となるだろうぜッ!!",
              characterName: "スピードワゴン"),
        Quote(quote: "こいつはくせえッー!\nゲロ以下のにおいが\nプンプンするぜッーーーーッ!!",
              characterName: "スピードワゴン"),
        Quote(quote: "心だ!\nあの人には今\n心が必要なんだッ!!",
              characterName: "スピードワゴン"),
        Quote(quote: "スピードワゴンはクールに去るぜ",
              characterName: "スピードワゴン"),
        Quote(quote: "ねーちゃん!\nあしたって\nいまさッ!",
              characterName: "ポコ"),
        Quote(quote: "この言葉をおまえに捧げよう!\nLuck!(幸運を)\nそして\n君の未来へこれを持って行けッ!\nPLUCK(勇気をッ!)",
              characterName: "ブラフォード"),
        Quote(quote: "なにジョジョ？\nダニーがおもちゃの鉄砲を\nくわえてはなさない？\nジョジョ　それは無理矢理\n引き離そうとするからだよ\n逆に考えるんだ\n「あげちゃってもいいさ」と\n考えるんだ",
              characterName: "ジョージ・ジョースター"),
        Quote(quote: "エリナ・ジョースターは…\nあなたと伴に死にます",
              characterName: "エリナ・ジョースター"),
        Quote(quote: "「勇気」とは\n「怖さ」を知ることッ!\n「恐怖」を我が物とする\nことじゃあッ!",
              characterName: "ウィル・A・ツェペリ"),
        Quote(quote: "ジョジョは\n悲しすぎる過去と\n重すぎる未来への責任を\n背負っているから\nできるのだ",
              characterName: "ウィル・A・ツェペリ"),
        Quote(quote: "これが運命なら\nあるがまま\n受け入れよう!",
              characterName: "ウィル・A・ツェペリ"),
        Quote(quote: "ある人間の不幸ってのは\nある人間を幸福にする\nウワッハハハハーーーッ",
              characterName: "ダリオ・ブランドー"),
        Quote(quote: "まあ!\nジョジョったらいけないひとッ!",
              characterName: "エリナ・ベンドルトン"),
        Quote(quote: "さすがディオ!\nおれたちができない事を\n平然とやってのけるッ\nそこにシビれる!\nあこがれるゥ!",
              characterName: "ディオの友人"),
        Quote(quote: "フフフ…\nこの「痛み」こそ「生」のあかし\nこの「痛み」あればこそ\n「喜び」も感じることができる\nこれが人間か…………",
              characterName: "ブラフォード"),
        Quote(quote: "わたしは最後に\n自分の全てを伝えた\n……………\nジョジョ…おまえはわしの希望だ!\nまるで親友と息子を同時に\n持ったような気持ちだぞ\nそして　わしはこれから\nお前の中で生きるんじゃ…",
              characterName: "ウィル・A・ツェペリ"),
        Quote(quote: "わたしも\n貧困の中に生まれたなら\n同じことをしていたかもしれない………\n……………指輪を売って\n家族になにか買ってやってください…\nそしてもう悪の人ではなく\n善の人になるのです",
              characterName: "ジョージ・ジョースター"),
        Quote(quote: "人間讃歌は「勇気」の讃歌ッ!!\n人間のすばらしさは勇気のすばらしさ!!",
              characterName: "ウィル・A・ツェペリ")
    ]
    
    // 2部
    static let quote2 = [
        Quote(quote: "師範代……\nあんたのしごきに対して\n礼をいうぜ……\nグラッツェ!ロギンス!",
              characterName: "ジョセフ・ジョースター"),
        Quote(quote: "ハッピー\nうれピー\nよろピくねぇ〜",
              characterName: "ジョセフ・ジョースター"),
        Quote(quote: "生き残るためには\n手段は選ばないもんネーー\nボクちゃん………\nルンルン",
              characterName: "ジョセフ・ジョースター"),
        Quote(quote: "この勝負…\nついてるネ\nのってるネ",
              characterName: "ジョセフ・ジョースター"),
        Quote(quote: "またまた\nやらせていただき\nましたァン!",
              characterName: "ジョセフ・ジョースター"),
        Quote(quote: "オー!\nノーッ\nおれの嫌いな言葉は\n一番が「努力」で\n二番目が「ガンバル」\nなんだぜーッ",
              characterName: "ジョセフ・ジョースター"),
        Quote(quote: "逃げるんだよォォォーーーーッ",
              characterName: "ジョセフ・ジョースター"),
        Quote(quote: "そうさ!\nワムウ!\n戦いは　戦いで別\nシーザーの死の\n悲しみは悲しみで別……\nおれも　なぜか\nあんたに対して\n敬意をはらいたく\nなったのさ………",
              characterName: "ジョセフ・ジョースター"),
        Quote(quote: "タコス",
              characterName: "ドイツ軍人"),
        Quote(quote: "ウィン\nウィン\nウィン\nウィン\nウィン",
              characterName: "カーズ"),
        Quote(quote: "ワムウ!\nやつは戦闘者として\nあまりにも純粋すぎた!\nそれが弱さに\nつながったのだ!!",
              characterName: "カーズ"),
        Quote(quote: "勝てばよかろうなのだァァァァッ!!",
              characterName: "カーズ"),
        Quote(quote: "しかし\nその無惨なる姿!\n美しいぞ!",
              characterName: "カーズ"),
        Quote(quote: "先生も知るように\nおれの決闘の問題だ!\nツェペリ一族の\n問題なのです",
              characterName: "シーザー・A・ツェペリ"),
        Quote(quote: "おれが最後に\nみせるのは\n代代受け継いだ\n未来にたくす\nツェペリ魂だ!\n人間の魂だ!",
              characterName: "シーザー・A・ツェペリ"),
        Quote(quote: "老いた今!\nなにものをも\n超えた生き物と\nなりたいと願う!",
              characterName: "ストレイツォ"),
        Quote(quote: "HEEEEYYYY\nあアアァんまり\nだアアアア",
              characterName: "エシディシ"),
        Quote(quote: "や…やつは「神」に\nなったんだ…!\n我われ…人間は\nか…「神」にだけは\n勝てない!\n服従しかないんだ!",
              characterName: "シュトロハイム"),
        Quote(quote: "それで\nおれの脚を\n断て!",
              characterName: "シュトロハイム"),
        Quote(quote: "そして　死にたいと思っても死ねないので|nーそのうちカーズは　考えるのをやめた。",
              characterName: "ナレーション"),
        Quote(quote: "おれの前で\n決闘を侮辱するな!\nJOJO!",
              characterName: "ワムウ"),
        Quote(quote: "おれにとって\n強い戦士こそ真理………\n尊敬する者!!\nシャボン玉のように\n華麗ではかなき男よ",
              characterName: "ワムウ"),
        Quote(quote: "人間の寿命は\nどうせ短い\n死にいそぐ\n必要もなかろう",
              characterName: "ワムウ")
    ]
    
    // 3部
    static let quote3 = [
        Quote(quote: "オラオラオラオラオラオラオラオラオラオラオラオラオラオラオラーッ",
              characterName: "空条承太郎"),
        Quote(quote: "『道』というものは\n自分で切り開く\nものだ",
              characterName: "空条承太郎"),
        Quote(quote: "「無理」だと？\nこの旅は無理な\nことばかりして来た\n旅だった…\n無理だとか無駄だとか\nいった言葉は\n聞きあきたし\nおれたちには関係ねえ",
              characterName: "空条承太郎"),
        Quote(quote: "さあ!\n賭ける(コール)か!\n賭けない(ドロップ)のか!\nハッキリ\n言葉に出して\n言ってもらおうッ!",
              characterName: "空条承太郎"),
        Quote(quote: "じじい　おれは　なにも\n考えてないぜ　ただ…\nあそこにすわっている\n『このゲームだけは\n誰にも負けない』と\n確固たる自信を持っている\nゲス野郎の鼻骨を\nブチ折ってやることだけ\nを考えている",
              characterName: "空条承太郎"),
        Quote(quote: "恐怖した動物は\n降伏のしるしとして\n自分のハラを見せるそうだが……\nゆるしてくれということか?\nしかし　てめーはすでに\n動物としてのルールの領域を\nはみ出した……\nだめだね",
              characterName: "空条承太郎"),
        Quote(quote: "だが　こんなおれにも\nはき気のする「悪」はわかる!!\n「悪」とは\nてめー自身のためだけに弱者を利用し\nふみつけるやつのことだ!!",
              characterName: "空条承太郎"),
        Quote(quote: "おめーの「スタンド」は被害者自身にも\n法律にも\n見えねえし\nわからねえ…\nだから\nおれが裁く!",
              characterName: "空条承太郎"),
        Quote(quote: "子供の頃\n『刑事コロンボ』が\n好きだったせいか\nこまかいことが\n気になると\n夜もねむれねえ",
              characterName: "空条承太郎"),
        Quote(quote: "やれやれだぜ…",
              characterName: "空条承太郎"),
        Quote(quote: "やれやれ\nてめー\n正真正銘の\n史上最低なおとこだぜ……\nてめーのつけは\n金では払えねーぜッ!",
              characterName: "空条承太郎"),
        Quote(quote: "もう\nてめーには\nなにもいうことはねえ…\n………\nとてもアワれすぎて\n何も言えねえ",
              characterName: "空条承太郎"),
        Quote(quote: "理解したか?\n(ドウー・ユー・アンダスタン?)",
              characterName: "空条承太郎"),
        Quote(quote: "バレなきゃあ\nイカサマじゃあ\nねえんだぜ\n……………",
              characterName: "空条承太郎"),
        Quote(quote: "つけの領収証だぜ",
              characterName: "空条承太郎"),
        Quote(quote: "てめーの敗因は…\nたったひとつだぜ…\n…DIO…\nたったひとつの\n単純(シンプル)な答えだ\n………\n『てめーはおれを怒らせた』",
              characterName: "空条承太郎"),
        Quote(quote: "大声で笑いながら\nするのが　作法だぞ　ポルナレフ!\n笑え!笑え!　ポルナレフ!",
              characterName: "モハメド・アヴドゥル"),
        Quote(quote: "HELL 2U!(ヘルトゥーユー!)",
              characterName: "モハメド・アヴドゥル"),
        Quote(quote: "わたしは\nもしこの館の中で\nお前が行方不明になったり\n負傷しても\n助けないつもりでいる…",
              characterName: "モハメド・アヴドゥル"),
        Quote(quote: "占い師の\nわたしに\n予言で\n闘おうなどとは\n10年は\n早いんじゃあ\nないかな",
              characterName: "モハメド・アヴドゥル"),
        Quote(quote: "「相手が\n勝ち誇ったとき\nそいつはすでに\n敗北している」",
              characterName: "ジョセフ・ジョースター"),
        Quote(quote: "確実!\nそうコーラを飲んだら\nゲップが出るっていうくらい\n確実じゃッ!",
              characterName: "ジョセフ・ジョースター"),
        Quote(quote: "これじゃあ…\n甲子園優勝チームに\nバットもったことがない\n茶道部か　なにかが\n挑戦するようなもの…\nみじめ…すぎる……",
              characterName: "ジョセフ・ジョースター"),
        Quote(quote: "わしのことは　もう気にするな…\nなるべくしてなったことなんじゃ",
              characterName: "ジョセフ・ジョースター"),
        Quote(quote: "わしらの失ったものは\nこの地球にも匹敵するほど大きい…\nしかし…彼らのおかげだ…\n彼らのおかげで\nわしらは生きて\nいるのじゃ…",
              characterName: "ジョセフ・ジョースター"),
        Quote(quote: "50年昔\nイタリアであの人と\n知り合って以来\n期待を裏切られたことは\nただの一度として\nありません……\nあの人は一度やると\n決心したら必ず\nやりたがる人です",
              characterName: "スージー・Q・ジョースター"),
        Quote(quote: "無駄無駄無駄無駄無駄無駄無駄無駄無駄",
              characterName: "DIO"),
        Quote(quote: "おれは「恐怖」を\n克服することが\n「生きる」\nことだと思う\n世界の頂点に立つ者は!\nほんのちっぽけな「恐怖」をも\n持たぬ者ッ!",
              characterName: "DIO"),
        Quote(quote: "「世界(ザ・ワールド)」\n時や止まれッ!\nWRYYYYYY\nYYYYーーッ",
              characterName: "DIO"),
        Quote(quote: "時は動き出す!",
              characterName: "DIO"),
        Quote(quote: "静止した時の中を動けるのは\nたったひとりでなくてはならない…\n思うに\n自動車という機械は\n便利なものだが\n誰も彼もが乗るから\n道路が混雑してしまう",
              characterName: "DIO"),
        Quote(quote: "うむむむ〜〜んんんんんん\nこの肉体に実にしっくり\nなじんで\nパワーが今まで以上に\n回復できたぞ\nなじむ\n実に!　なじむぞ\nフハハハハハ　フフフフ\nフハフハ　フハフハ",
              characterName: "DIO"),
        Quote(quote: "とるにたらぬ\n人間どもよ!\n支配してやるぞッ!!\n我が「知」と「力」のもとに\nひれ伏すがいいぞッ!",
              characterName: "DIO"),
        Quote(quote: "「人間は誰でも\n不安や恐怖を\n克服して安心を\n得るために生きる」",
              characterName: "DIO"),
        Quote(quote: "すべてはッ\nおのれの\n弱さを認めた\n時に始まる",
              characterName: "恋人(ラバーズ)"),
        Quote(quote: "史上最弱が\n……………\n最も恐ろしィィ\nマギィーッ!!",
              characterName: "恋人(ラバーズ)"),
        Quote(quote: "人間は\n心の底から願うことに\n最大の弱点全てが\nあらわれる",
              characterName: "審判(ジャッジメント)"),
        Quote(quote: "見捨てないでーッ\nヒィィィィィ\n孤独だよーっ",
              characterName: "アヌビス神"),
        Quote(quote: "今…感じる感覚は……\nおれは「白」の中に\nいるということだ…\nDIOは「黒」!\nジョースターさんたちは「白」\n「黒」と「白」がはっきり別れて感じられるぜ!\n傷ついた体でも勇気が湧いてくる\n「正しいことの白」の中におれはいるッ!",
              characterName: "ジャン・ピエール・ポルナレフ"),
        Quote(quote: "『我が名はJ・P・ポルナレフ』\n『我が妹の魂の名誉のために!』\n『我が友アヴドゥルの\n心のやすらぎのために』\n………\n『この俺が\n貴様を絶望の淵へ\nぶち込んでやる』",
              characterName: "ジャン・ピエール・ポルナレフ"),
        Quote(quote: "あ…ありのまま　今起こったことを話すぜ!\n『おれは　やつの前で階段を登っていた\nと思ったら　いつのまにか降りていた』\nな…何を言っているのかわからねーと思うが\nおれも　何をされたのかわからなかった…\n頭がどうにかなりそうだった…\n催眠術だとか超スピードだとか\nそんなチャチャなもんじゃあ断じてねえ\nもっと恐ろしいものの片鱗を味わったぜ……",
              characterName: "ジャン・ピエール・ポルナレフ"),
        Quote(quote: "奴はなんていうか…\n執念を持っている!\nクレイジーだが\nDIOに仕えるという\n執念を持っている!……\nその執念に圧倒されるなッ!\nおれの方だって　てめーを\nブッ殺すまでは死ねねーぜッ",
              characterName: "ジャン・ピエール・ポルナレフ"),
        Quote(quote: "おれには悲しい\n友情運があるぜ",
              characterName: "ジャン・ピエール・ポルナレフ"),
        Quote(quote: "自分の回りで\n死なれるのは\nスゲー迷惑だぜッ!\nこのオレはッ!",
              characterName: "ジャン・ピエール・ポルナレフ"),
        Quote(quote: "フフ…\nやはり\nこのまま\nいさぎよく\n焼け死ぬとしよう…\nそれが君との闘いに\n敗れたわたしの\n君の「能力」への礼儀……\n自害するのは無礼だな…",
              characterName: "ジャン・ピエール・ポルナレフ"),
        Quote(quote: "わたしの\n「法皇の緑(ハイエロファントグリーン)」は…\nひきちぎると\nくるい\nもだえるのだ\n喜びでな!",
              characterName: "花京院典明"),
        Quote(quote: "レロレロ\nレロレロレロ\nレロレロレロ\nレロレロレロ\nレロレロレロ\nレロレロレロ",
              characterName: "花京院典明"),
        Quote(quote: "『我が名は花京院典明』\n『我が友人アヴドゥルの\n無念のために\n左にいる友人ポルナレフの\n妹の魂のやすらぎのために』\n『死をもって\nつぐなわせてやる』",
              characterName: "花京院典明"),
        Quote(quote: "二度とあの時の\nみじめな花京院には\n絶対に戻らないッ!",
              characterName: "花京院典明"),
        Quote(quote: "さあ\nお仕置きの\n時間だよベイビー",
              characterName: "花京院典明"),
        Quote(quote: "「悪」?\n「悪」とは敗者のこと…\n「正義」とは勝者のこと\n………\n生き残った者のことだ\n過程は問題じゃあない\n敗けたやつが\n『悪』なのだ",
              characterName: "花京院典明"),
        Quote(quote: "それは\n仲なおりの\n「握手」のかわりだ",
              characterName: "花京院典明"),
        Quote(quote: "やれやれ…\n犬好きの\n子供は\n見殺し\nには\n……\nできねーぜ!",
              characterName: "イギー"),
        Quote(quote: "パンツーまる見え",
              characterName: "ポルナレフと花京院"),
        Quote(quote: "カモォ〜〜ン　ポルポルくぅ〜〜ん",
              characterName: "ホルホース"),
        Quote(quote: "女にうそはつくが\n女だけは\n殴ったことはねえ!\nブスだろうが\n美人だろうが\n女を尊敬して\nいるからだ!",
              characterName: "ホルホース"),
        Quote(quote: "わたしはね　賭けとは\n人間関係と同じ……\nだまし合いの関係と\n考えています\n泣いた人間の敗北\nなのですよ",
              characterName: "ダニエル・J・ダービー"),
        Quote(quote: "Exactly(そのとおりでございます)",
              characterName: "テレンス・T・ダービー"),
        Quote(quote: "もしかして\nオラオラ\nですかーッ!?",
              characterName: "テレンス・T・ダービー"),
        Quote(quote: "人間の魂というものは\n実に不思議だ\n「敗北」する時!\n自分の「敗北」を\n自分で認めた瞬間\n魂のエネルギーは\n限りなく0に近くなる\n………",
              characterName: "テレンス・T・ダービー"),
        Quote(quote: "触れてはいけない\n物というのは\n触れてしまいたく\nなるものね",
              characterName: "マライヤ"),
        Quote(quote: "『死ぬのはこわくない\nしかしあの人に　見捨てられ\n殺されるのだけはいやだ』\n悪には悪の救世主が\n必要なんだよ\nフフフフ",
              characterName: "ンドゥール"),
        Quote(quote: "チュミミ〜ン",
              characterName: "女帝(エンプレス)"),
        Quote(quote: "なめるように\n便器をきれいにするんじゃ\nなめるように!\nぬアアアめるよォ\nオオオオにィィィィ",
              characterName: "エンヤ婆")
    ]
    
    // 4部
    static let quote4 = [
        Quote(quote: "いいかい!\nもっとも\n『むずかしい事』は!\n『自分を乗り越える事』さ!\nぼくは\n自分の『運』を\nこれから\n乗り越える!!",
              characterName: "岸辺露伴"),
        Quote(quote: "方法はわからんが\nなんらかの\n『イカサマ』を\nしている………\nゆるせん\nその方法がわからない所が\nゆるせん!",
              characterName: "岸辺露伴"),
        Quote(quote: "『リアリティ』こそが\n作品に生命(いのち)を\n吹き込むエネルギーであり\n『リアリティ』こそが\nエンターテイメントなのさ",
              characterName: "岸辺露伴"),
        Quote(quote: "ぼくは\n『読んでもらうため』に\nマンガを描いている!\n『読んでもらうため』\nただそれだけのためだ\n単純なただひとつの\n理由だが\nそれ以外はどうでもいいのだ!",
              characterName: "岸辺露伴"),
        Quote(quote: "ぼくの「スタンド」\n『ヘブンズ・ドアー』\n………\n自分の『遠い記憶』\nと……『「運命」は読めない』………\n………か",
              characterName: "岸辺露伴"),
        Quote(quote: "だが\n断る\nこの岸辺露伴が\n最も好きな事のひとつは\n自分で強いと思ってる\nやつに「NO」と\n断ってやる事だ!",
              characterName: "岸辺露伴"),
        Quote(quote: "え…えと\nあなたのスタンドで\n『エコーズ』の目を\n傷つけて……\nぼくの目を\n見えないように\nしてください",
              characterName: "広瀬康一"),
        Quote(quote: "それに…\n愛している人のものなら　誰だって\nウンコだろうが　鼻汁だろうが\n平気でしょう?\n気にするのは　変だわ!\nむしろ　あなたの\nパンツ洗たくしてる時\nあたし幸せを感じたのよ…",
              characterName: "山岸由花子"),
        Quote(quote: "あんな\nうすらけがらわしい\nヤツがッ\n………\n『パパとママ』が住むこの町に\nいてはならないどッ!!",
              characterName: "矢安宮重清"),
        Quote(quote: "あなたたちの生きてる\n人間が町の\n『誇り』と『平和』を\n取り戻さなければ\nいったい\n誰が\nとり戻すって\nいうのよッ!",
              characterName: "杉本鈴美"),
        Quote(quote: "人間ってのは\n罪の重さに耐え切れなくなると\n死んだほうがましって思うんだぜ\n〜〜〜〜〜〜〜〜っ",
              characterName: "小林玉美"),
        Quote(quote: "おまえら一枚のCDを聞き終わったら\nキチッとケースにしまってから\n次のCDを聞くだろう?\n誰だって　そーする　おれもそーする",
              characterName: "虹村形兆"),
        Quote(quote: "ひとつだけ言える事を\n見つけたよ\nこの町の\n若者は\n『黄金の精神』を\nもっている\nという事をのォ",
              characterName: "ジョセフ・ジョースター"),
        Quote(quote: "人間は何かを\n破壊して生きていると\nいってもいい生物だ\nその中で\nお前の能力は\nこの世のどんな\nことよりもやさしい",
              characterName: "空条承太郎"),
        Quote(quote: "「どうか　このぼくに\n人殺しをさせてください」",
              characterName: "川尻早人"),
        Quote(quote: "おまえ味方する「運命」なんて………\nおまえがのれるかどうかの\n「チャンス」なんて………\n今!　ここにある　「正義の心」に比べれば\nちっぽけな力なんだッ!\n確実にここにある!!\n今　確かにここにある\n「心」に比べればなッ!",
              characterName: "川尻早人"),
        Quote(quote: "質問を質問で返すなあーっ!!\n疑問文には疑問文で答えろと\n学校で教えているのか？",
              characterName: "吉良吉影"),
        Quote(quote: "ひとつの「闘い」に\n勝利する事は簡単だ…\nだが次の「闘い」のために\nストレスがたまる……\n愚かな行為だ",
              characterName: "吉良吉影"),
        Quote(quote: "『勝ち負け』にこだわったり\n頭をかかえるような『トラブル』とか\n夜もねむれないといった『敵』を\nつくらない…というのが\nわたしの社会に対する姿勢であり\nそれが自分の幸福だということを\n知っている……\nもっとも　闘ったとしても\nわたしは誰にも負けんがね",
              characterName: "吉良吉影"),
        Quote(quote: "「思い込む」\nという事は\n何よりも\n「恐ろしい」\n事だ………",
              characterName: "吉良吉影"),
        Quote(quote: "誰も『爪』をのびるのを\n止めることがでしないように…\n持って生まれた「性(さが)」\nというものは　誰も\nおさえる事が　できない\n………………\nどうしようもない…\n困ったものだ",
              characterName: "吉良吉影"),
        Quote(quote: "君が　どこで誰に\n何をしようと\nわたしは「無敵」に\nなったんだ",
              characterName: "吉良吉影"),
        Quote(quote: "心は　みにくいが\n美しい手と顔を\nした女だ\nこのわたしの\nところに来れば\n清い心で\n付き合えるよ…",
              characterName: "吉良吉影"),
        Quote(quote: "だが　わたしには\n勝ち負けは問題ではない…\nわたしは『生きのびる』……\n平和に『生きのび』てみせる\nわたしは人を殺さずにはいられない\nという『サガ』を背負ってはいるが\n………………\n『幸福に生きてみせるぞ!』",
              characterName: "吉良吉影"),
        Quote(quote: "スゲーッ　爽やかな気分だぜ\n新しいパンツをはいたばかりの\n正月元旦の朝のよーによォ\n〜〜〜〜〜〜ッ",
              characterName: "東方仗助"),
        Quote(quote: "「切り抜ける」\nってのは\nちょいとちがいますね…\n『ブチ壊し抜ける』\n……!",
              characterName: "東方仗助"),
        Quote(quote: "おめーに\n『さよなら』って言葉が\nあるとするならよーっ\nおれたちが\n『さよなら』と\n言うのを\n聞く時だけだ!!",
              characterName: "東方仗助"),
        Quote(quote: "永遠に\n供養しろ!",
              characterName: "東方仗助"),
        Quote(quote: "死んだ人に\n言うのも\n何だけどよー\n元気でな",
              characterName: "東方仗助"),
        Quote(quote: "そして\nなにより\n死んだ人間は\nどうしようもない",
              characterName: "東方仗助")
    ]
    
    // 5部
    static let quote5 = [
        Quote(quote: "必ずやるって決めた時は「直線」だッ!\n今のオレは　何がなんでも「直線」で\n突っ切るのよッ!",
              characterName: "ペッシ"),
        Quote(quote: "兄貴の覚悟が!\n「言葉」でなく「心」で理解できた!",
              characterName: "ペッシ"),
        Quote(quote: "「ブッ殺す」と\n心の中で思った\nならッ!\nその時スデに\n行動は終わっているんだッ!",
              characterName: "プロシュート"),
        Quote(quote: "ディ・モールト\nディ・モールト\n(非常に　非常に)\n良いぞッ!",
              characterName: "メローネ"),
        Quote(quote: "スゴクいい!\nいいビンタだ!!",
              characterName: "メローネ"),
        Quote(quote: "アバッキオ\nおまえはりっぱにやったのだ\nそしておまえの\n真実に『向かおうとする意志』は\nあとの者たちが感じとって\nくれているのさ\n大切なのは…　そこなんだからな……",
              characterName: "アバッキオの元同僚"),
        Quote(quote: "「結果」だけを求めていると\n人は近道をしたがるものだ…………\n近道をした時\n真実を見失うかもしれない\nやる気もしだいに失せていく\n大切なのは\n『真実に向かおうとする意志』\nだと思っている",
              characterName: "警官"),
        Quote(quote: "ああ…\n1つ目はな\n………「うそをつかない」だ\n2つ目は\n「うらまない」…\nそして\n3つ目は\n相手を「敬う」…いいだろ?\n友情の3つの『U(ユー)』だ",
              characterName: "涙目のルカ"),
        Quote(quote: "人が人を選ぶにあたって\n最も大切なのは『信頼』なんだ\nそれに比べたら\n頭がいいとか才能があるなんて事は\nこのクラッカーの\n歯クソほどのこともないんだ…",
              characterName: "ポルポ"),
        Quote(quote: "『柔ラカイ』トイウ事ハ\n『ダイヤモンド』ヨリモ壊レナイッ!!",
              characterName: "スパイス・ガール"),
        Quote(quote: "倒すとか倒さないとかは\nあたしにとっては別問題だわ!\nあたしはどうしても知りたい!自分が何者から生まれたのかをッ!それを知らずに殺されるなんて\nまっぴらゴメンだわッ!",
              characterName: "トラッシュ・ウナ"),
        Quote(quote: "ボラボラボラボラ\nボラボラボラボラ\nボラーレ・ヴィーア\n(飛んで行きな)",
              characterName: "ナランチャ・ギルガ"),
        Quote(quote: "強者は弱いやつらを支配してもいい\n資格があるのだ\nいや……\n他人を支配しなくてはならない\n宿命が　強いものにはあるのだ…",
              characterName: "チョコラータ"),
        Quote(quote: "絶望をわたしの方に\n向けながら\n落下していけえええ\nえええええええ",
              characterName: "チョコラータ"),
        Quote(quote: "アリアリアリアリアリアリアリアリ\nアリアリアリアリアリアリアリアリ\nアリアリアリアリアリアリ\nアリーヴェデルチ!\n(さよならだ)",
              characterName: "ブローノ・ブチャラティ"),
        Quote(quote: "この味は!\n………\nウソをついてる\n『味』だぜ……",
              characterName: "ブローノ・ブチャラティ"),
        Quote(quote: "まるで「10年」も修羅場を\nくぐり抜けて来たような……\nスゴ味と……冷静さを\n感じる目だ………\nたったの数分で　こんなにも\n変わるものか……",
              characterName: "ブローノ・ブチャラティ"),
        Quote(quote: "今何もしないってのが…\n………\nオレの…「覚悟」だ……!!",
              characterName: "ブローノ・ブチャラティ"),
        Quote(quote: "答えろよ\n質問はすでに…\n『拷問』に変わっているんだぜ",
              characterName: "ブローノ・ブチャラティ"),
        Quote(quote: "吐き気をもよおす『邪悪』とはッ！\n何も知らぬ無知なる者を\n利用する事だ……!!",
              characterName: "ブローノ・ブチャラティ"),
        Quote(quote: "ゆるさねえッ!\nあんたは今　再びッ!\nオレの心を\n『裏切った』ッ!",
              characterName: "ブローノ・ブチャラティ"),
        Quote(quote: "終わったものは\nどうすることもできないってな\nオレの「命」は…\nあの時　すでに終わっていたんだ",
              characterName: "ブローノ・ブチャラティ"),
        Quote(quote: "運命とは\n『眠れる奴隷』だ\n……\nオレたちはそれを\n解き放つことができた……",
              characterName: "ブローノ・ブチャラティ"),
        Quote(quote: "オレは\n「正しい」と\n思ったからやったんだ\n後悔はない…\nこんな世界とはいえ　オレは\n自分の『信じられる道』を\n歩いていたい!",
              characterName: "ブローノ・ブチャラティ"),
        Quote(quote: "「ブッ殺してやる」\nって\nセリフは…\n終わってから言うもんだぜ\nオレたち\n「ギャングの世界」\nではな",
              characterName: "ブローノ・ブチャラティ"),
        Quote(quote: "見なくてもいいものを見たものは!!\nこの世に存在しては\nならねーんだぜッ!",
              characterName: "ヴィネガー・ドッピオ"),
        Quote(quote: "誰が言った言葉\n………だったか………\n『我々はみな運命に選ばれた兵士』…",
              characterName: "ディアボロ"),
        Quote(quote: "オレは「帝王」だ\nオレが目指すものは\n『絶頂であり続ける』ことだ\nここで逃げたら…\nその『誇り』が失われる\n次はないッ……!",
              characterName: "ディアボロ"),
        Quote(quote: "「過去」というものは\n人間の真の平和を\nがんじがらめにする",
              characterName: "ディアボロ"),
        Quote(quote: "生き残るのは\n…………\nこの世の「真実」だけだ\n……\n真実から出た『誠の行動』は\n…………\n………\n決して滅びはしない………",
              characterName: "ジョルノ・ジョバァーナ"),
        Quote(quote: "『侮辱する』という\n行為に対しては\n殺人も許されるだって?\nなるほど\n……おまえの言う事は\n本当に大切な事だ\nおまえは\nあの無関係のじいさんの\n『命を侮辱した』",
              characterName: "ジョルノ・ジョバァーナ"),
        Quote(quote: "なぜなら…\n2度言うってのは無駄だからだ…\n君の人生のために言うけど……\n無駄は　やめた方がいい",
              characterName: "ジョルノ・ジョバァーナ"),
        Quote(quote: "「覚悟」とは\n………………\n犠牲の心ではないッ!\n「覚悟」とは!!\n暗闇の荒野に!!\n進むべき道を切り開く事だッ!",
              characterName: "ジョルノ・ジョバァーナ"),
        Quote(quote: "終わりのないのが『終わり』",
              characterName: "ジョルノ・ジョバァーナ"),
        Quote(quote: "この\nジョルノ・ジョバァーナ\nには　正しいと信じる\n夢がある",
              characterName: "ジョルノ・ジョバァーナ"),
        Quote(quote: "あなたの「覚悟」は…\nこの登りゆく朝日よりも\n明るい輝きで『道』を照らしている\nそして我々が\nこれから\n『向かうべき…正しい道』をもッ!",
              characterName: "ジョルノ・ジョバァーナ")
    ]
    
    // 6部
    static let quote6 = [
        Quote(quote: "落ちつくんだ…\n『素数』を数えて\n落ちつくんだ…\n『素数』は1と自分の\n数でしか割ることの\nできない孤独な数字……\nわたしに勇気を与えてくれる",
              characterName: "エンリコ・プッチ神父"),
        Quote(quote: "悪い出来事の未来も\n知る事は「絶望」と思うだろうが\n逆だッ!\n明日「死ぬ」とわかっていても\n「覚悟」があるから幸福なんだ!\n「覚悟」は「絶望」を\n吹き飛ばすからだッ!",
              characterName: "エンリコ・プッチ神父"),
        Quote(quote: "『なるようにしかならない』\nという力には\n無理に逆らったりするな……\n『天国へ行く』\nという事は\nそれさえも味方に\nするという事だからだ",
              characterName: "エンリコ・プッチ神父"),
        Quote(quote: "「どこへ行かれるのですか?」\n(ドミネ・クオ・ヴァディス)\nおまえは「磔刑(たっけい)」だーーーーッ!!",
              characterName: "エンリコ・プッチ神父"),
        Quote(quote: "無償の愛とは……\n天国へ行くための\n「見返り」\nだからだ",
              characterName: "エンリコ・プッチ神父"),
        Quote(quote: "思い出のない人間は\n死人と同じだ",
              characterName: "エンリコ・プッチ神父"),
        Quote(quote: "人が敗北する原因は…\n「恥」のためだ\n人は「恥」のために死ぬ",
              characterName: "エンリコ・プッチ神父"),
        Quote(quote: "君は\n「引力」を\n信じるか?\nわたしに　躓いて\n転んだ事に意味が\nある事を!?",
              characterName: "DIO"),
        Quote(quote: "『通じた』\nのよ……\n今……\n倒産を理解出来たと\n体で感じる……",
              characterName: "空条徐倫"),
        Quote(quote: "父さんなら神父を\n絶対に\n逃がさないッ!\nあたしは\n空条徐倫ッ\nあいつが得たものを\n「封印」しなければ\nならないッ!",
              characterName: "空条徐倫"),
        Quote(quote: "『ひとりの囚人は\n壁を見ていた』\n……\n『もうひとりの囚人は\n鉄格子からのぞく星を見ていた』あたしは　どっちだ?",
              characterName: "空条徐倫"),
        Quote(quote: "ウェザー\nもう一度………\nもう一度話がしたい\nあなたと\nそよ風の中で\n話がしたい",
              characterName: "空条徐倫"),
        Quote(quote: "生きのびるのよ\nあんたは「希望」!!",
              characterName: "空条徐倫"),
        Quote(quote: "人はみんな\n『あしたは月曜日』ってのは\n嫌なもんなんだ　でも…\n必ず『楽しい土曜日がやってくる』\nって思って生きている",
              characterName: "エルメェス・コステロ"),
        Quote(quote: "「復讐」とは自分の運命への\n決着をつけるためにあるッ!",
              characterName: "エルメェス・コステロ"),
        Quote(quote: "グロリアのぶんだあああ\nーーーーーッ\nこれも!これも!これも!\nこれも!これも!これも!これも!\nこれも!これも!",
              characterName: "エルメェス・コステロ"),
        Quote(quote: "つまり「知性」という力は\nビックバンより先に存在していて\n全ての物質や生物は「知性」に\n導かれ　その「知性」をすでに\n保有しているのだ",
              characterName: "フー・ファイターズ"),
        Quote(quote: "おまえは「運命」に負けたんだ!\n「正義の道」を歩む事こそ「運命」なんだ!!",
              characterName: "エンポリオ・アルニーニョ"),
        Quote(quote: "死ぬ事以上に\n不幸な事が\n起こるんだよ",
              characterName: "エンポリオ・アルニーニョ"),
        Quote(quote: "おまえは………\n自分が\n『悪』だと気づいていない…\nもっともドス黒い『悪』だ…",
              characterName: "ウェザー・リポート"),
        Quote(quote: "祝福しろ　結婚にはそれが必要だ",
              characterName: "ナルシソ・アナスイ"),
        Quote(quote: "俺の心は『アポロ11号』\nだ\nオレは\nおまえの上を\n行く……",
              characterName: "リキエル"),
        Quote(quote: "神父の\n求めているものは\nその「偶然」だ!",
              characterName: "リキエル")
    ]
    
    // 7部
    static let quote7 = [
        Quote(quote: "民主主義だからみんなで決めてるか?\nそれとも自由競争か?\n違うッ!!\nナプキンを取れる者が\n決めている!",
              characterName: "ファニー・ヴァレンタイン"),
        Quote(quote: "我が心と行動に一点の曇りなし\n…………！\n全てが『正義』だ",
              characterName: "ファニー・ヴァレンタイン"),
        Quote(quote: "男が女にひかれる基準だが…\nあるいは\n女が男にひかれる基準だが…………\n「愛」だとか「愛してない」だとか\n「好き」だとか「嫌い」だとか\nそんなんじゃあない\n…………\n「吉」であるかどうかだ",
              characterName: "ファニー・ヴァレンタイン"),
        Quote(quote: "ここまでの旅\nいったい何本の「河」を\nぼくらは渡って来たのだろう……\nそして　あといくつの「河」を\n渡るのだろう……",
              characterName: "ジョニィ・ジョースター"),
        Quote(quote: "「本物」を探せ…\n自分の眼で…\n「本物」を見なければ\n回転しないッ!",
              characterName: "ジョニィ・ジョースター"),
        Quote(quote: "ぼくはまだ\n「マイナス」なんだッ!\n「ゼロ」に向かって行きたいッ!\n「遺体」を手に入れて\n自分の「マイナス」を\n「ゼロ」に戻したいだけだッ!!",
              characterName: "ジョニィ・ジョースター"),
        Quote(quote: "ジャイロ……\n迷ったなら『撃つな』…\n…………だ!\nだがもう『迷い』はない",
              characterName: "ジョニィ・ジョースター"),
        Quote(quote: "「飢えなきゃ」勝てない\nただしあんなDioなんかより\nずっとずっともっと気高く\n「飢え」なくては!",
              characterName: "ジョニィ・ジョースター"),
        Quote(quote: "信じたかった\n本当に…大統領を信じたかった\nさようなら\nジャイロ\n…………\nさようなら",
              characterName: "ジョニィ・ジョースター"),
        Quote(quote: "「ありがとう」…\nそれしか言う言葉が\nみつからない…",
              characterName: "ジョニィ・ジョースター"),
        Quote(quote: "絶対に友達は\n彼の祖国へ連れて帰る\n……絶対にだ!",
              characterName: "ジョニィ・ジョースター"),
        Quote(quote: "そしてひとつひとつの河を渡る\n今＿＿最後の河を渡り終わった＿＿＿",
              characterName: "ジョニィ・ジョースター"),
        Quote(quote: "「納得」は全てに\n優先するぜッ!!\nでないとオレは「前」へ進めねえッ!",
              characterName: "ジャイロ・ツェペリ"),
        Quote(quote: "ついてくるか?\nルートは最短をとるぜ…",
              characterName: "ジャイロ・ツェペリ"),
        Quote(quote: "だがクセなんて直さなくていい\nもっとクセを出して走れ",
              characterName: "ジャイロ・ツェペリ"),
        Quote(quote: "ピザ・モッツァレラ♪\nピザ・モッツァレラ♪\n♪レラレラレラレラ♪\n♬レラレラレラレラ\nレラレラレラレラ♩♪\nピザ・モッツァレラ♪",
              characterName: "ジャイロ・ツェペリ"),
        Quote(quote: "オレはこのSBRレースで\nいつも最短の近道を試みたが\n『一番の近道は遠回りだった』\n『遠回りこそが俺の最短の道だった』\nこの大陸を渡ってくる間\nずっとそうだった\nそして　おまえがいたから\nその道を渡って来れた",
              characterName: "ジャイロ・ツェペリ"),
        Quote(quote: "君はオレが攻撃したら\nそれに『対応』しようとしている\nそれが心体にこびりついている\n『才能』ではすぐれたものが\nあるのかもしれないが\nこびりついた『正当なる防衛』では\nオレを殺す事は決して出来ない\n受け身の『対応者』はここでは必要なし",
              characterName: "リンゴォ・ロードアゲイン"),
        Quote(quote: "ようこそ………\n『男の世界』へ……………",
              characterName: "リンゴォ・ロードアゲイン"),
        Quote(quote: "偶然じゃあない\n「選ばれた」……「奇跡」だよ\nジャイロ・ツェペリ",
              characterName: "ウェカピポ"),
        Quote(quote: "ベッドの上で死ぬなんて\n期待してなかったさ\nオレはカウボーイだからな\n帰る所が欲しかっただけさ…\n………\n旅に出たら帰る場所がな…………",
              characterName: "マウンテン・ティム"),
        Quote(quote: "男には地図が必要だ…\n荒野を渡り切る\n心の中の地図がな",
              characterName: "グレゴリオ・ツェペリ"),
        Quote(quote: "テニスの競技中…\nネット　ギリギリにひっかかって\nはじかれたボールは……\nその後　ネットのどちら側に\n落下するのか…?\n誰にもわからない\nそこから先は「神」の領域だ",
              characterName: "グレゴリオ・ツェペリ"),
        Quote(quote: "人は\n何かを捨てて\n前へ進む",
              characterName: "アクセル・RO(ロー)"),
        Quote(quote: "「全て」を\n敢えて差し出した者が\n最後には\n真の「全て」を得る",
              characterName: "シュガー・マウンテン"),
        Quote(quote: "白人は「敵」だ\nだが……\n敵から身を守るには\n「敵」の文化をよく知らなくちゃあ\nならないって考え方だってあるんだ",
              characterName: "砂男(サンドマン)"),
        Quote(quote: "真の『失敗』とはッ!\n開拓の心を忘れ!\n困難に挑戦する事に\n無縁のところにいる\n者たちの事をいうのだッ!\nこのレースに失敗なんか\n存在しないッ!\n存在するのは冒険者だけだッ!",
              characterName: "スティーブン・スティール"),
        Quote(quote: "スティールという性\nあってこそのルーシー",
              characterName: "ルーシー・スティール"),
        Quote(quote: "「圧迫祭り」よッ!\nお顔を\n圧迫してッ!",
              characterName: "スカーレット・ヴァレンタイン"),
        Quote(quote: "愛し始めていたのに…………\nずっとずっと\n目をかけてあげようと\n思っていたのに………!!\nこのあばずれがァァーーーーーッ\nこの乳房を両方とも\n弾丸で削りとってやるッ!",
              characterName: "スカーレット・ヴァレンタイン"),
        Quote(quote: "おお……\n……神よ……\nあなたは…\n連れて行く\n子供を\n間違えた…\n………",
              characterName: "ジョニー・ジョースターの父"),
        Quote(quote: "どうぞ…\nシチューをいただけますか?\nかまいません……\nこの手の中へ……\n注いでいただけますか?\nディオの分を……",
              characterName: "Dioの母"),
        Quote(quote: "「愛国心」は\nこの世でもっとも美しい「徳」だ\n子を守るため命をかけるのは\n動物も同じだが\n国の誇りのため\n命をかける事が\n家族を守る事に\nつながると考えるのは\n「人間の気高さ」だけだ",
              characterName: "陸軍騎兵隊大尉ヴァレンタイン"),
        Quote(quote: "「感傷」とら\n心の「スキ間」であり\n「弱さ」＿＿＿＿＿",
              characterName: "ナレーション")
    ]
    
    // 8部
    static let quote8 = [
        Quote(quote: "勝ったのはオレです\nあ…もう一度たっぷり言わせていただきます\n勝ったのは……オレです!\nたっぷり！",
              characterName: "東方定助"),
        Quote(quote: "常敏さん言わせて頂きます\nたっぷりと……\nどうやら勝っちゃいました…\n勝ったのは……\nオレの方だなああ────",
              characterName: "東方定助"),
        Quote(quote: "『S&W 越えて行く\n（ソフトアンドウェット ゴー・ビヨンド）』\nそのしゃぼん玉は\nどこにも存在しない",
              characterName: "東方定助"),
        Quote(quote: "オレはいったい誰なんだッ!?\n答えろォオオオォォ\nーーーーーーーッ!!",
              characterName: "東方定助"),
        Quote(quote: "『王手飛車取り』と言ったが\n違うな…!!\nオレのは『詰み』だッ!",
              characterName: "東方定助"),
        Quote(quote: "この天と地の下に存在している\n『S&W（ソフト・アンド・ウェット）』!\n……柔らかくて　濡れていて\n回転している……",
              characterName: "東方定助"),
        Quote(quote: "2階はヤバイ!\nホラー映画でも\n2階に逃げたキャラは死ぬッ!!",
              characterName: "東方定助"),
        Quote(quote: "もし負けたなら…\n『オレは進むべき道を進めなくなる!』",
              characterName: "東方定助"),
        Quote(quote: "君がどうしても嫌というのなら…\nあるいは君の心を\nオレが傷つけるというのなら\nそういうことはしないよ",
              characterName: "東方定助"),
        Quote(quote: "悪人は生まれた時から悪人\nなのだろうか?\nもし「悪人」になっていくとしたら\nそれは「欲望」や「ねたみ」のためか…?\n「怠惰」や「憤怒」のためか?\nそれとも「無邪気さ」のため\nなのだろうか?",
              characterName: "東方定助"),
        Quote(quote: "なんだこれはぁぁ──────ッ\nンマイなあああッ!!",
              characterName: "東方定助"),
        Quote(quote: "なんか喋ったかあ～～～\n聞こえないなあ　オレはもう聞きたくない\n フザけたセリフは聞かないことにした!",
              characterName: "東方定助"),
        Quote(quote: "ヤツは…\n『決してこちらから追う事は出来ない』\n『追わせるのは良い』",
              characterName: "東方定助"),
        Quote(quote: "自分のことだ…\n直接自分で行って自分の目と耳で知りたい",
              characterName: "東方定助"),
        Quote(quote: "ポテトＬサイズが好き\nポテトＬサイズが好き\nポテトＬサイズが好き\nでもフライドチキンはない\nフライドチキンはない\nフライドチキンはない\nカリカリのそれだけでいい\nポテトＬサイズが好き",
              characterName: "東方定助"),
        Quote(quote: "だが『見えない回転』があるんだ\nその『見えないヤツ』が\n 君のペイズリー・パーク(P・P)と一緒に\nこの携帯を越えてそっちへ行った!",
              characterName: "東方定助"),
        Quote(quote: "フーン　オレのスニーカーは\nアウトレットでナナキュッパだ",
              characterName: "東方定助"),
        Quote(quote: "行くぞ！「Go★Beyond」",
              characterName: "東方定助"),
        Quote(quote: "奥歯で噛むのッ!\n奥歯で!",
              characterName: "広瀬康穂"),
        Quote(quote: "いつも見えているものは\n物事の「結果」だけだ\n真実が必要ならば「ふり出し」に戻って\n探さなくてはならない\n全ては「原点」から始まるものだから…",
              characterName: "広瀬康穂"),
        Quote(quote: "「ジョジョリオン」…これは\n「呪い」を解く物語",
              characterName: "広瀬康穂"),
        Quote(quote: "出逢うタイミングが…\n良いね…　いつも僕たち…",
              characterName: "透龍"),
        Quote(quote: "あとひとつだ　君がこれからあとひとつ\nそれがどんなちっぽけな事であろうとだ\n例えば君が僕や僕のスタンドを\n追いかけるような行為を只の一つ\n「何か」やらかしたなら\n死ぬ順番は直ちに『君から』になる\nそして終結へと向かう",
              characterName: "透龍"),
        Quote(quote: "厄災に正義は無い　悪との区別も無い",
              characterName: "透龍"),
        Quote(quote: "君は座ってなよ\nの場所に寝てるか…\nそのまま黙って途方に暮れてろ",
              characterName: "透龍"),
        Quote(quote: "君楽しいね\nまたいつか会えるといいな\n大人になって……君が僕を忘れた頃に…",
              characterName: "透龍"),
        Quote(quote: "今…………一匹………\nスズメ蜂が…いたんだが………\nそうか…思い出…なのか…僕の……",
              characterName: "透龍"),
        Quote(quote: "このわたしを『追跡する』行為は\n必ず『禍(わざわい)』の痛手となって\nその者に返って行く『厄災の流れ』は\n『条理の流れ』だからだ!\nこの世の『理(ことわり)』は\n連続して繋がっている!\n決して!それを超えて来るなどという事は\nありえない！",
              characterName: "明負悟"),
        Quote(quote: "おっと答えにくい質問だったかな…\nなぜ答えないのか…？\nもしくはまだ手に入れてはいないのかな",
              characterName: "豆鉄礼"),
        Quote(quote: "優先順位はわたしを守る事が「第1位」だぞ…\n君自身の命は「2位」になる",
              characterName: "豆鉄礼"),
        Quote(quote: "くどいようだが…89さいか?",
              characterName: "豆鉄礼"),
        Quote(quote: "『誰もそれには気づいていない』……\n『誰にもそれはスタンドでも見えていない』\n「線」だ　「線」が…回転している\nお前のしゃぼん玉は\n柔らかい「線」が回転している!",
              characterName: "豆鉄礼"),
        Quote(quote: "やっぱり返せェェェーーーーッ!!\n返せよォォ!!\nそれはオレのものだッ!",
              characterName: "東方常秀"),
        Quote(quote: "グロ注意ッ！グロ注意ッ！\n頭がちぎれるぞォ！",
              characterName: "東方常秀"),
        Quote(quote: "全ては夏休みのように\n幸福で輝いているんだよ……\nこれからもずっとな",
              characterName: "東方常敏"),
        Quote(quote: "人ってのは…\n何かを乗り越えようとしている時が\n『幸福』なんだ　それは恵まれて…\n大金持ちの家に生まれた長男でも\nそうなんだよ　更に登って進まなきゃあ…\n決して『幸せ』にはならない\n相対性さ",
              characterName: "東方常敏"),
        Quote(quote: "つまづいたっていいじゃないか……\n人間だもの",
              characterName: "東方常敏"),
        Quote(quote: "覚悟を……決めろ…!!\nさもなくば…………口を閉じろ",
              characterName: "東方常敏"),
        Quote(quote: "もしいつかおまえが\n「病気」になるとしたら…\nもしその時が来るのなら\nおまえの時はパパが「治して」やる\n必ず「治して」やる",
              characterName: "東方常敏"),
        Quote(quote: "オレの父さんがなんだかんだ\n綺麗事を言っても\n強いヤツが残り…弱いヤツは消える!\n只のそれだけだし\nこの世の誰だろうと\nこの流れを止める事は出来ない",
              characterName: "東方常敏"),
        Quote(quote: "僕って他の子供たちと比べて\n「幸せ」なのかなぁ…\n「幸せ」じゃないのかなぁ…\n同じくらいなのかなぁ\n「何が」そろっていれば\n「幸せ」なのかなぁ",
              characterName: "東方つるぎ"),
        Quote(quote: "禁じ手だけどやらなきゃ殺られていた…\n光で照らされたなら…\nあたしはその中へ進むッ!!",
              characterName: "東方つるぎ"),
        Quote(quote: "自分自身で「弱点」と思ってない所が\nまた「弱点」!",
              characterName: "東方つるぎ"),
        Quote(quote: "どけて　これの事よ\nなれなれしくわたしの肩に手をのせるな\n手じゃなかった\nお前の前足をどけろ",
              characterName: "東方密葉"),
        Quote(quote: "「知らなかった」で逃げたら…\n幸せになれない",
              characterName: "東方密葉"),
        Quote(quote: "治療に2億円支払ったわ",
              characterName: "東方密葉"),
        Quote(quote: "流れて消えろッ!",
              characterName: "東方密葉"),
        Quote(quote: "『公正さこそルール』\n『ルールこそパワー』なの…",
              characterName: "東方大弥"),
        Quote(quote: "真の「幸せ」って考えたことあるぅ\n本当の「幸せ」を…\nわたしはすでにわかっている\n「幸せ」っていうのは……\n「思い出」を誰かと共有することよ",
              characterName: "東方大弥"),
        Quote(quote: "愛してもらうの……\nその思い出に浸るのォ…",
              characterName: "東方大弥"),
        Quote(quote: "ごく当たり前のことを断っておく\nわたしにウソはつくなよ",
              characterName: "田最環"),
        Quote(quote: "どけ!わたしが歩くのに邪魔だろーがッ!",
              characterName: "田最環"),
        Quote(quote: "今回だけは……\nただの一度だけは…許して欲しい\n知らない他の誰かが\n身代わりでもいいではないか…\n妻が助かればそれでいい……\n一度だけ…お願いです 一回だけで……",
              characterName: "ジョニィジョースター"),
        Quote(quote: "ジョージ・ジョースター\nお前に会えてよかった…\nそれだけで…いいんだ…",
              characterName: "ジョニィジョースター")
    ]
}
